name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['darwin','linux','windows']
        arch: ['386','amd64','arm','arm64']
        exclude:
          - os: darwin
            arch: '386'
          - os: darwin
            arch: 'arm'
          - os: windows
            arch: 'arm'

    steps:
    - uses: actions/checkout@v7

    - uses: pnpm/setup@v3
      with:
        version: 12
        cache: true
        runtime: node@lts
        working-directory: server/client/
        require-lockfile: true
        install: true

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'

    - name: Build Web UI
      run: |
        pnpm -C server/client/ lint
        pnpm -C server/client/ build
      env:
        VITE_APP_VERSION: ${{ github.event.release.name }}

    - name: Build CLI
      run: |
        ARCHIVE_NAME="zt-dl-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
        CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build \
            -o '_out/' \
            -ldflags "-s -w \
                -X github.com/rokeller/zt-dl/cmd.version=${{ github.event.release.name }}"
        
        tar -cvzf "$ARCHIVE_NAME" -C _out $(ls -A _out)
        echo "ARCHIVE_PATH=$ARCHIVE_NAME" >> "$GITHUB_ENV"
        echo "ARCHIVE_MEDIA_TYPE=application/gzip" >> "$GITHUB_ENV"

    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ${{ env.ARCHIVE_PATH }} ${{ env.ARCHIVE_MEDIA_TYPE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
